#!/bin/sh
# $Id: mk,v 1.13 2016-11-08 12:25:22-08 - - $

cat >test1.in <<__END__
eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
tttttttttttttttttttttttttttttttttttttttt
aaaaaaaaaaaaaaaaaaaa
oooooooooooooooooooo
__END__

cat >test2.in <<__END__
eeeeeeeeeeeeeeeeeeee eeeeeeeeeeeeeeeeeeee eeeeeeeeee
eeeeeeeeeeeeeeeeeeee eeeeeeeeeeeeeeeeeeee eeeeeeeeee
tttttttttttttttttttt tttttttttttttttttttt
aaaaaaaaaaaaaaaaaaaa
oooooooooooooooooooo
iiiiiiiiii
nnnnn
sssss
h
r
__END__

cat >test3.in <<__END__
aaaaaaaaaa aaaaaaaaaa aaaaaaaaaa aaaaaaaaaa
bbbbbbbbbb bbbbbbbbbb bbbbbbbbbb bbbbbbbbbb
cccccccccc cccccccccc cccccccccc cccccccccc
dddddddddd dddddddddd dddddddddd dddddddddd
eeeeeeeeee eeeeeeeeee eeeeeeeeee eeeeeeeeee
ffffffffff ffffffffff ffffffffff ffffffffff
gggggggggg gggggggggg gggggggggg gggggggggg
hhhhhhhhhh hhhhhhhhhh hhhhhhhhhh hhhhhhhhhh
iiiiiiiiii iiiiiiiiii iiiiiiiiii iiiiiiiiii
jjjjjjjjjj jjjjjjjjjj jjjjjjjjjj jjjjjjjjjj
__END__

cid $0 phuffman.perl
for infile in test?.in
do
   outfile=$(echo $infile | sed s/in/out/)
   lisfile=$(echo $infile | sed s/in/lis/)
   phuffman.perl <$infile >$outfile 2>&1
   more $infile $outfile >$lisfile </dev/null
done
mkpspdf Listing.ps test?.lis $0 phuffman.perl
